### ISSUE TITLE
[bug] URLエンコードされたパスを使用している際に Unexpected token が発生する

### ISSUE THREAD

**Issue by kazuemon** [aspida/pathpida#125]
## Description

URLエンコードされたパスを使用している際（`pages/%E6%97%A5%E6%9C%AC%E8%AA%9E/index.tsx` => `/日本語`）に、生成されるファイルが以下のようになり Unexpected token でエラーとなります。
```typescript
export const pagesPath = {
  %E6%97%A5%E6%9C%AC%E8%AA%9E: {
    $url: (url?: { hash?: string }) => ({ pathname: '/%E6%97%A5%E6%9C%AC%E8%AA%9E' as const, hash: url?.hash }),
  },
};
```

### Expected

```typescript
export const pagesPath = {
  '%E6%97%A5%E6%9C%AC%E8%AA%9E': {
    $url: (url?: { hash?: string }) => ({ pathname: '/%E6%97%A5%E6%9C%AC%E8%AA%9E' as const, hash: url?.hash }),
  },
};
```

## Environment

- **Package version:**
  
  `v0.18.0`
- **Using with:** Next.js
- **OS:**
  
  - Linux
- **Node.js version:**
  
  `v14.18.2`
- **npm version:**
  
  `v8.3.2`

**Comment by kazuemon** [comment]
修正ありがとうございます🙇

**Comment by LumaKernel** [comment]
ありがとうございます!
修正されたバージョンがすぐにリリースされます。

aspida 関連の話にもなりますが、 https://github.com/aspida/aspida/issues/724 で、さらに網羅的な命名へのサポートについて議論したりしています。 upvoteが増えると優先されて議論されていくかもしれません。
