### ISSUE TITLE
gitのコンフリクト対策

### ISSUE THREAD

**Issue by tmatz** [aspida/pathpida#171]
## Description

$path.tsでQueryに通し番号が振られますがgitでコンフリクトしやすいです。

インポートパスからハッシュ値や型名に使える文字列に変換することで差分を局所化できないでしょうか。

**Comment by solufa** [comment]
私は$path.tsをgitignoreに入れているのでこの需要に全く気が付きませんでした

Next.jsがpathpida相当の機能を持つらしいのでその後も需要がありそうかどうかで修正を決めます

**Comment by solufa** [comment]
v0.22.0で対応済み
