### ISSUE TITLE
Next.js App RouterのDynamic Routesに対するエラー

### ISSUE THREAD

**Issue by hiterm** [aspida/pathpida#180]
## Description

Next.jsのApp Routerを利用し、Dynamic Routesに対するリンクを作成しようとすると、以下のエラーが発生します。

```
Error: Dynamic href `/items/[itemId]` found in <Link> while using the `/app` router, this is not supported. Read more: https://nextjs.org/docs/messages/app-dir-dynamic-href
```

## Environment

- **Package version:**
  
  `v0.20.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v18.15.0`
- **npm version:**
  
  `9.6.1`

## Additional context

以下のサンプルコードで、問題を再現して確認いただけます。

立ち上げた上で http://localhost:3000/items にアクセスしてみてください。

https://github.com/hiterm/2023-06-05-pathpida-nextjs-app-router-example

**Comment by solufa** [comment]
v0.21.0で対応
