### ISSUE TITLE
staticPath の basepath オプションへのサポート

### ISSUE THREAD

**Issue by LumaKernel** [aspida/pathpida#24]
Pathpida を create-frourio-app に組み込む、というロードマップがあるかと思うのですが、試しにフロントエンドを GitHub Pages で basepath を使ってデプロイした際に、

```ts
  const { basePath } = useRouter()

// ...
          <img
            src={`${basePath}/vercel.svg`}
            alt="Vercel Logo"
            className={styles.logo}
          />
```

と、自分で `basePath` をおいて上げる必要がありました。

- https://nextjs.org/docs/api-reference/next.config.js/basepath
- https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/

このとき、もし pathpida を現在の仕様で入れると、

```ts
  const { basePath } = useRouter()

// ...
          <img
            src={`${basePath}/${staticPath.vercel_svg}`}
            alt="Vercel Logo"
            className={styles.logo}
          />
```

となります。
好みの範囲かもしれませんが、型安全に、プロパティが存在することと、static path が存在することを同一にするというのがゴールだとすれば、 `staticPath` は事前に config から `basePath` を取って含めておいてくれたほうがいいかもしれない、ということを思いました。つまり、basepath があっても以下のように書けたほうが嬉しいかもしれない、ということです。

```ts
// ...
          <img
            src={staticPath.vercel_svg}
            alt="Vercel Logo"
            className={styles.logo}
          />
```

もしくは `staticPath.vercel_svg.$full_path()` と `staticPath.vercel_svg.$path()` など… 名付けが難しいですしこれは微妙かもしれません。

**Comment by solufa** [comment]
破壊的変更でいいので「basepath があっても以下のように書けたほうが嬉しい」のパターンで行こう！

**Comment by solufa** [comment]
v0.12.0のリリースで対応完了です
PRありがとうございました！
