### ISSUE TITLE
似た名前のファイルとフォルダがある場合にキーが重複する

### ISSUE THREAD

**Issue by yuta-ike** [aspida/pathpida#46]
## Description
Next.jsでpathpidaのGenerate static files pathを利用させていただいております。

`public/`以下で、`public/image-png`というフォルダと、`public/image.png`というファイルのように、ハイフンかドット違いのアイテムが存在する場合、`$path.ts`内の`staticPath`で、`image_png`というキーが重複して生成されてしまいます。

```
export const staticPath = {
  image_png: {
    ....
  },
  image_png: '/image.png',
}
```

## Environment

- **Package version:**
  `v0.13.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  `v14.15.1`
- **npm version:**
  `7.5.3`

## Additional context
Next.js `v10.0.6`

**Comment by solufa** [comment]
バグ報告ありがとうございます！
修正作業に入りました
命名規則に悩んでおりリリースは明日くらいになりそうです

**Comment by yuta-ike** [comment]
ご確認ありがとうございます！

**Comment by solufa** [comment]
お待たせしました、修正リリースしたのでご確認ください
重複がないパスは今まで通り、重複する場合はプロパティ名の末尾に連番が付与されます

**Comment by yuta-ike** [comment]
ありがとうございます！！（frourioもaspidaもひっそり応援しています...!）
