### ISSUE TITLE
[Feature request] Include/exclude filename pattern

### ISSUE THREAD

**Issue by mkobayashime** [aspida/pathpida#64]
## Description

Thanks a lot for this sick library.

I'm using Next.js with CSS Modules to style pages/components, and the `pages` directory looks like this.

```
pages
  |- index.tsx
  |- index.module.scss
  |- profile.tsx
  |- profile.module.scss
     ...
```

The problem here is that pathpida generates page typedefs for `*.module.scss` files too. It's not something fatal, but could leads to some typing mistakes as the editor actually suggests `pagesPath.profile_module` (this PAGE doesn't exist!) as well as `pagesPath.profile` (disired one, apparently) when you type `pagesPath.prof...`.

## Describe the solution you'd like

Include/exclude pattern.

```
yarn pathpida --include "*.tsx"
or
yarn pathpida --exclude "*.module.scss"
```

## Describe alternatives you've considered

Adding underscore `_` as prefix to all the `*.module.scss` files solves the problem itself, but is not very elegant imo.

**Comment by solufa** [comment]
Thank you for posting this.
I've had similar requests from other users, so I'll see what I can do.
I may change it to ignore scss/css extensions by default so that it can be used immediately without any configuration.

**Comment by solufa** [comment]
Supported in v0.15.0.
