### ISSUE TITLE
Ignore dotfiles or files ignored by .gitignore

### ISSUE THREAD

**Issue by ka2n** [aspida/pathpida#77]
## Description

`staticPath`に`.DS_Store`などのファイルが混ざらないようにして欲しいです。

### Solution1: ファイル名が`.`からはじまる場合に含めない

e.g. https://github.com/ka2n/pathpida/commit/680893a420a06dcd96f23a225cdb61f0150fe6dc

### Solution2: .gitignoreを読み込む

https://github.com/kaelzhang/node-ignore や https://github.com/npm/ignore-walk などを利用し、`.gitignore`を使用してファイルを無視することもできそうです。
e.g. https://github.com/ka2n/pathpida/commit/967a75f61476447cc94a47910adeb296f175667a

**Comment by solufa** [comment]
提案ありがとうございます
v0.16.0で対応しました
https://github.com/aspida/pathpida#command-line-interface-options
