### ISSUE TITLE
Cannot find module 'next/dist/next-server/server/config'

### ISSUE THREAD

**Issue by dc7290** [aspida/pathpida#84]
## Description

Next.js 11.1.0において 'next/dist/next-server/server/config' はエクスポートされていないため、

`Cannot find module 'next/dist/next-server/server/config'`

のエラーに遭遇します。

## Environment

- **Package version:**
  `v0.15.4`
- **OS:**
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  `14.17.4`
- **yarn version:**
  `1.22.10`

## Additional context

Next.js 11.1.0

**Comment by d-chiba-q** [comment]
Next.js11.1.0から
`next/dist/server/config`
でエクスポートされているようです 。

**Comment by dc7290** [comment]
Next.js11.1.0から
`next/dist/server/config`
でエクスポートされているようです 。

**Comment by solufa** [comment]
@dc7290 
バグ報告ありがとうございます！
v0.15.5 で修正されたはずです
ご確認ください
