### ISSUE TITLE
want to be able to set the directory to output the `$path.ts` file.

### ISSUE THREAD

**Issue by tsuki-lab** [aspida/pathpida#87]
sorry. I am not good at English, so I will draft in Japanese.

## Description
現状、utilsとlibの二つのディレクトリが存在するときに優先的にutilsに`$path`ファイルが出力される。

## Describe the solution you'd like

$path.tsの出力先を`.pathpida.config.js`もしくは、`--output`オプションで設定できるようにしてほしい。

## Describe alternatives you've considered

libとutilsの二つのディレクトリが存在しないようにディレクトリ構成を検討しました。

例）`lib/utils/**`, `lib/$path.ts`

**Comment by solufa** [comment]
提案ありがとうございます
v0.16.0で対応しました
https://github.com/aspida/pathpida#command-line-interface-options
