### ISSUE TITLE
Support `pageExtensions` for Next.js

### ISSUE THREAD

**Issue by odanado** [aspida/pathpida#89]
## Description

Next.js can use pageExtensions to set the extension. ref: https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions.
If you use `page.tsx` for this extension, pathpida will generate the wrong type definition file.

|file|expect|actual|
|-|-|-|
|`pages/hello.page.tsx`| `pagesPath.hello` | `pagesPath.hello_page` |
| `pages/post/[id].page.tsx` | `pagesPath.post._id` | `pagesPath.post.[id]_page` |

## Environment

- **Package version:**
  
  `v0.16.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  - v14.17.3
  - 
- **yarn version:**
  - 1.22.10

## Additional context
Here is a repository that reproduces the bug.
https://github.com/odan-sandbox/next-pathpida-page-extensions-sandbox

**Comment by solufa** [comment]
提案ありがとうございます。
v0.17.0 で対応しました。
