### ISSUE TITLE
[Next.js] Generate `pathname` as actual URL being navigated to

### ISSUE THREAD

**Issue by nandorojo** [aspida/pathpida#94]
## Description

Currently, generating a page path looks like this:

```ts
pagesPath.asset._symbol(ticker.symbol).$url()
```

And the result is this:

```js
{
  "hash": undefined,
  "pathname": "/asset/[symbol]",
  "query": {
    "symbol": "AAPL",
  },
}
```

## Describe the solution you'd like

I want the `pathname` to return the actual URL (`/asset/AAPL`), rather than `/asset/[symbol]`

Say I'm navigating to `/asset/[symbol]`, and `symbol = 'AAPL'`

```ts
pagesPath.asset._symbol('AAPL').$url()
```

I'd want the result to include the actual URL path that it's navigating to as the `pathname`:

```js
{
  "hash": undefined,
  "pathname": "/asset/AAPL",
  "query": {
    "symbol": "AAPL",
  },
}
```

With Next.js 9.4+, we no longer need to use the `/asset/[symbol]` syntax. I want to know the actual URL, since I need this for redirect URLs and more.

## Describe alternatives you've considered

I've considered a regex that replaces every instance of `[some-string]` with the corresponding value from `query`. But this isn't ideal. 

[You can see it for yourself here](https://stackblitz.com/edit/nextjs-lf9o3i?file=pages%2Findex.js). Note that Stackblitz has its own routing, so if you want to see the URL change, you have to click **Open in new window** in the top right.

**Comment by kqito** [comment]
Hi.

I'm recently wanting like this feature in a case where I wanted to get the actual path from pathpida to set for such as SEO 

So I'm wondering if pathpida has plans to provide this feature or like `asPath` in the future ;)
