### ISSUE TITLE
Doesn't work with NX

### ISSUE THREAD

**Issue by aamir-mns** [aspida/pathpida#95]
## Description

We are using [NX](https://nx.dev/) and our nextjs folder is under `root/apps/app-name/pages/page-name.tsx`. Not sure if there is a way to use pathpida here.

## Describe the solution you'd like

Allow CLI option to pass path to the pages folder which can default to the current logic that pathpaida supports

## Describe alternatives you've considered

Just loop through all folders and look for pages folder? not sure it's a good idea.

## Additional context

I think this line needs to accept cli option https://github.com/aspida/pathpida/blob/master/src/getConfig.ts#L49

**Comment by nandorojo** [comment]
We just called `cd apps/next && pathpida ...` in the root.

**Comment by aamir-mns** [comment]
@nandorojo Perfect. Thanks

**Comment by aamir-mns** [comment]
Re-opening since the problem is not solved yet.
If we use `cd apps/app-name && pathpida`, I get an error since pathpida cannot find the package.json file inside that folder. NX use just one package.json file which lives in the root. Looking at the code in [getConfig.ts](https://github.com/aspida/pathpida/blob/master/src/getConfig.ts#L17-L20) file, it's trying to find the framework used. Can this be a CLI option too e.g. `--framework`?
I know this is a special use case using NX where nextjs app and package.json lives on separate paths but ideally with adding a couple of more CLI option will make it work with NX too.
